[package]
name = "tetris-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4" # Check https://crates.io/crates/rand for the latest version
crossterm = "0.22.1" # Check for the latest version on crates.io

[[bin]]
name = "main"
path = "main.rs"
